# Generated by Django 2.0.13 on 2019-08-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cod_barras',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
