# Generated by Django 2.0.13 on 2019-08-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_produto_cod_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cod_barras',
            field=models.CharField(max_length=100),
        ),
    ]
