# Generated by Django 2.0.13 on 2019-08-20 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_produto_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
    ]
