# Generated by Django 2.0.13 on 2019-08-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190819_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='nome',
            new_name='cinome',
        ),
    ]
